# Generated by Django 5.2.3 on 2025-06-28 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_document_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchcache',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='raw_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stitchcache',
            name='location_versions_hash',
            field=models.TextField(),
        ),
    ]
